@startuml
skinparam linetype ortho
entity "Patient" as p {
id
ФИО
Статус
Дата рождения
Контактные данные
}
entity "Doctor" as d {
id
ФИО
Специализация
Стаж работы
Квалификационная категория
Сертификаты и лицензии
Должность
Дата рождения
Контактные данные
График работы
}
entity "Office" as of {
id
Номер кабинета
}
entity "Appointment" as ap {
id
Время записи
Статус
пациент
кабинет
врач
услуга
}
entity "Service" as s {
id
name
}
entity "AppointmentService" as as {
id_appointment
id_service
}
entity "DoctorService" as ds {
id_doctor
id_service
}
entity "DoctorOffice" as do {
id_doctor
id_office
}
entity "DoctorPatient" as dp {
id_doctor
id_patient
}

d ||--|{ do
of ||--o{ do
d ||--|{ ds
s ||--o{ ds
d ||--o{ dp
p ||--o{ dp
p |o--o{ ap
ap }o--|| d
ap }o--|| of 
ap ||--o{ as
s ||--o{ as
@enduml
