@startuml
title "Авторизация пользователя"
actor Пользователь as user
participant "Форма авторизации (Front)" as ID_form
participant "Сервис авторизации (Back)" as ID_service
database    "База данных пользователей"    as db
user -> ID_form++: Ввод логина
activate user
user <- ID_form : Отображение логина
user -> ID_form: Нажатие кнопки "Далее"
ID_form-> ID_service++: Запрос на проверку логина
ID_service -> db++: Проверить существование логина
Break "Пользователь не зарегистрирован в системе"
   ID_service <<-- db: Логин не существует
   ID_form    <<-- ID_service: Вернуть ошибку идентификации
   user <<-- ID_form: Отобразить ошибку идентификации
end
ID_service <<-- db: Логин существует
ID_form    <<-- ID_service: Идентификация прошла успешно
user <<-- ID_form: Отобразить форму для ввода пароля
user ->> ID_form: Ввод пароля
user ->> ID_form: Нажатие кнопки "Далее"
ID_form-> ID_service: Запрос на аутентификацию
ID_service -> ID_service: Найти хэш пароля
ID_service -> db: Проверить соответсвие хэшей
Break "Авторизация не удалась"
   ID_service <<-- db: Вернуть информацию о несовпадении хэшей
   ID_form    <<-- ID_service: Вернуть ошибку аутентификации
   user <<-- ID_form: Отобразить сообщение о неверном пароле
end
ID_service <<-- db--: Вернуть информацию о совпадении хэшей и правах пользователя
ID_service -> ID_service: Генерация JWT
ID_form    <<-- ID_service--: Ответ об успешной авторизации, передача JWT
user <<-- ID_form--: Отобразить страницу в соответсвие с правами доступа
deactivate user
@enduml
